/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_psort_psortj_modhmm_modhmmjni */

#ifndef _Included_org_psort_psortj_modhmm_modhmmjni
#define _Included_org_psort_psortj_modhmm_modhmmjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_psort_psortj_modhmm_modhmmjni
 * Method:    gethelices
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_psort_psortj_modhmm_modhmmjni_gethelices
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     org_psort_psortj_modhmm_modhmmjni
 * Method:    helixcount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_psort_psortj_modhmm_modhmmjni_helixcount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_psort_psortj_modhmm_modhmmjni
 * Method:    helixstart
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_psort_psortj_modhmm_modhmmjni_helixstart
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_psort_psortj_modhmm_modhmmjni
 * Method:    helixend
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_psort_psortj_modhmm_modhmmjni_helixend
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_psort_psortj_modhmm_modhmmjni
 * Method:    helixdestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_psort_psortj_modhmm_modhmmjni_helixdestroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
