/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_psort_psortj_hmmer_hmmerjni */

#ifndef _Included_org_psort_psortj_hmmer_hmmerjni
#define _Included_org_psort_psortj_hmmer_hmmerjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_psort_psortj_hmmer_hmmerjni
 * Method:    hmmsearch
 * Signature: (Ljava/lang/String;IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_psort_psortj_hmmer_hmmerjni_hmmsearch
  (JNIEnv *, jobject, jstring, jint, jint, jstring);

/*
 * Class:     org_psort_psortj_hmmer_hmmerjni
 * Method:    destroyreport
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_psort_psortj_hmmer_hmmerjni_destroyreport
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_psort_psortj_hmmer_hmmerjni
 * Method:    countglobalhits
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_psort_psortj_hmmer_hmmerjni_countglobalhits
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_psort_psortj_hmmer_hmmerjni
 * Method:    countdomainhits
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_psort_psortj_hmmer_hmmerjni_countdomainhits
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_psort_psortj_hmmer_hmmerjni
 * Method:    getindivglobalscore
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_org_psort_psortj_hmmer_hmmerjni_getindivglobalscore
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_psort_psortj_hmmer_hmmerjni
 * Method:    getindivdomainscore
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_org_psort_psortj_hmmer_hmmerjni_getindivdomainscore
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_psort_psortj_hmmer_hmmerjni
 * Method:    getindivglobalpvalue
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_org_psort_psortj_hmmer_hmmerjni_getindivglobalpvalue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_psort_psortj_hmmer_hmmerjni
 * Method:    getindivglobalevalue
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_org_psort_psortj_hmmer_hmmerjni_getindivglobalevalue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_psort_psortj_hmmer_hmmerjni
 * Method:    getindivdomainpvalue
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_org_psort_psortj_hmmer_hmmerjni_getindivdomainpvalue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_psort_psortj_hmmer_hmmerjni
 * Method:    getindivdomainevalue
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_org_psort_psortj_hmmer_hmmerjni_getindivdomainevalue
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
